//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System.Linq;
using System.Web.Security;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web.UI.WebControls;
using System.Xml.Linq;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web;
using System.Configuration;
using System;
using System.Text;
using System.Web.Profile;
using System.Web.Caching;
using System.Collections;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.WebControls.Expressions;
using System.Collections.Specialized;
using System.Web.SessionState;
using System.Web.DynamicData;

public class signup_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState {
protected global::System.Web.UI.WebControls.TextBox TextBox1;
protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
protected global::System.Web.UI.WebControls.RadioButton RadioButton1;
protected global::System.Web.UI.WebControls.RadioButton RadioButton2;
protected global::System.Web.UI.WebControls.Calendar Calendar1;
protected global::System.Web.UI.WebControls.TextBox TextBox2;
protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
protected global::System.Web.UI.WebControls.TextBox TextBox3;
protected global::System.Web.UI.WebControls.TextBox TextBox4;
protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
protected global::System.Web.UI.WebControls.TextBox TextBox5;
protected global::System.Web.UI.WebControls.CompareValidator CompareValidator1;
protected global::System.Web.UI.WebControls.Button Button1;
protected global::System.Web.UI.HtmlControls.HtmlForm form1;
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.Profile.DefaultProfile Profile {
get {
return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
}
}
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
}
}
private string Bind(string expression, string format) {
return "";
}
private string Bind(string expression) {
return "";
}
}
}
